Adding Script file, HTML and CSS file for the mini-project
MinhTuan2405/mini_project_js pull request #1
Opened 2024-09-19 13:54 UTC by MinhTuan2405

### Description:
- **Summary**: This PR introduces the following changes:
  1. Added a new JavaScript (`.js`) for the logic of the game.
  2. Created a new HTML (`.html`) file to build the frame for the game.
  3. Added corresponding CSS (`.css`) file to style HTML.
  4. Inserted comments in both the JS and HTML files to improve code clarity and documentation.

- **Game logic**:

Starting the game, the system automatically generates a secret number, The player has to enter his guessing number, if it matches with the secret number, he will win, otherwise, he will lose one point. Giving 20 scores the first time, if the score is lower than 1, the player will lose the game

- **Review request**:
  Please focus on:
  1. JavaScript logic and any potential improvements.
  2. HTML structure for semantic correctness.
  3. Coding standard in the JS file 
  4. Clarity and effectiveness of comments in the JS and HTML files.

2024-09-19 14:58 UTC, thangphanmoso requested changes
PR title em nên sửa lại có ý nghĩa hơn ví dụ Add feature/fix bug/...
Ngoài ra em deploy sử dụng github pages và dẫn link vào PR description để a test được luôn mà ko cần phải pull code về nhe

2024-09-19 14:58 UTC, thangphanmoso commented on index.html
> +    <!-- style -->
CS5.2: em add empty line phía trên để tách biệt các block nhe

2024-09-19 14:58 UTC, thangphanmoso commented on index.html
> +    <meta charset="UTF-8" />
CS5.2: em thêm comment phía trên cho block này nhe

2024-09-19 14:58 UTC, thangphanmoso commented on index.html
> +    <title>Guess My Number!</title>
CS5.2: em thêm empty line phía trên và bổ sung comment cho block này nhe

2024-09-19 14:58 UTC, thangphanmoso commented on index.html
> +    <script src="main.js"></script>
CS5.2: em phân tách đoạn code này thành các block tương ứng với trên UI ví dụ như title, submit button,... sau đó thêm empty line giữa các block để dễ đọc hơn và bổ sung comments cho từng block nhe

2024-09-19 14:58 UTC, thangphanmoso commented on index.html
> +      <p class="between">(Between 1 and 20)</p>
CS5.1: em đặt tên class có ý nghĩa hơn nhe tương tự với tất cả chỗ khác

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +const checkButton = document.querySelector ('.check')
CS1: get btn để add event handler em move xuống cùng với nơi xử lý event handler sẽ liền mạch dễ đọc code hơn

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +const backgroud = document.querySelector ('body')
CS1: những variables này em define ở nơi sử dụng nó ko nên define trên cùng rồi ở dưới mới sử dụng làm code ko liến mạch khó để đọc code

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +const randomNewSecret = () => {
CS5: em đặt tên hàm phản ánh chính xác với mục đích sử dụng của nó ngoài ra bổ sung thêm P trong IPO nhe

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +const reset = () => {
CS5: em đặt tên hàm phản ánh chính xác với mục đích sử dụng của nó ngoài ra bổ sung thêm P trong IPO nhe

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +    guess.innerHTML = ''
CS5.2: em bổ sung step-by-step comment và thêm các empty line chia tách các block xử lý để dễ đọc code hơn. em update tương tự với những đoạn code khác

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +let highestScore = 0
CS1: a thấy biến này được define nhưng ko được reassign do đó phải là constant

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +    }
CS1: code của em khá nhiều nested if else nên khó đọc. em follow theo gợi ý trước đó a đã comment trong report để update nhe

2024-09-19 14:58 UTC, thangphanmoso commented on main.js
> +                currentScore.innerHTML = score
CS1: chỗ này em có thể viết gọn lại. em update tương tự phía dưới

2024-09-20 16:14 UTC, thangphanmoso requested changes
a thử thì thấy logic này chưa work ` if the score is lower than 1, the player will lose the game`. em check lại nhe

2024-09-20 16:14 UTC, thangphanmoso commented on index.html
> +      <button class="btn again">Again!</button>
CS5.1: em nên đặt tên class giống với ý nghĩa button hơn. ví dụ như `playAgainBtn` chẳng hạn

2024-09-20 16:14 UTC, thangphanmoso commented on index.html
> +        <button class="btn check">Check!</button>
CS5.1: em đặt tên class giống với ý nghĩa button hơn

2024-09-20 16:14 UTC, thangphanmoso commented on index.html
> +        <p class="message">Start guessing...</p>
CS5.1: em đặt tên class rõ ràng hơn là display message gì. ở đây message thì khá chung chung có vẻ là cho cả error, success,...

2024-09-20 16:14 UTC, thangphanmoso commented on index.html
> +        <p class="label-score">💯 Score: <span class="score">20</span></p>
CS5.1: em đặt tên class có ý nghĩa hơn dựa trên content mà nó show. ví dụ ở đây có thể là `currentScore` hay `userScore` gì đó

2024-09-20 16:14 UTC, thangphanmoso commented on index.html
> +        </p>
CS5: highscore và highest score là khác nhau em sửa lại đồng nhất nhe

2024-09-20 16:14 UTC, thangphanmoso commented on main.css
> +  /* background-color: #60b347; */
CS1: đối với style ko sử dụng nữa em nên remove luôn thay vì comment lại

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +    backgroud.style.backgroundColor = color
CS5.2: a thấy những phần code ntn là thể hiện 1 action gì đó vì vậy em nên start comment bằng active verb

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +// Process: return the secret number through the random method in Math object
CS5.2: a thấy có vẻ em generate random number từ 1 -> 20. nếu đúng thì em bổ sung comment chi tiết hơn nhe

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +    return Math.trunc (Math.random () * 20) + 1
CS1: a thấy có vẻ em generate random number từ 1 -> 20. em nên đặt constant lên trên cùng file cho 2 value này để sau này muốn thì mình có thể sửa lại rule game từ 20 -> 40 chẳng hạn

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +// Process: reset all the element of game, ignore the high score information
CS5.2: em nên comment rõ hơn là reset những gì

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +    guess.innerHTML = ''
CS5.2: đối với các functions chứa nhiều steps như vậy em nên đánh số steps để dễ follow logic nhe
```
// 1. display....
// 2. create...
...
```

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +    backgroud.style.backgroundColor = color
CS5.2: đối với các functions chứa nhiều steps như vậy em nên đánh số steps để dễ follow logic nhe

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +let score = 20
CS5.1: em đặt tên biến phản ánh với data nó hold nhe

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +const secret = document.querySelector ('.secretnumber')
CS5.1: em đặt tên biến phản ánh đúng data nó hold nhe

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +})
CS5.2: đối với các functions chứa nhiều steps như vậy em nên đánh số steps để dễ follow logic nhe

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +    }
CS1: a check thấy logic này ko worked

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +    }
ngoài ra nếu như user đã ko nhập gì thì a nghĩ các đoạn code phía dưới cũng ko nên được chạy nữa

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +        currentScore.innerHTML = score--
CS1: logic trước đó của em là
```
--score
currentScore.innerHTML = score
```
như vậy khi đổi qua logic mới này có vẻ chưa chính xác. hoặc logic ban đầu của em chưa chính xác

2024-09-20 16:14 UTC, thangphanmoso commented on main.js
> +document.querySelector ('.again').addEventListener ('click', resetGame ())
CS1: a check thì thấy có vẻ logic này chưa work

2024-09-20 17:10 UTC, MinhTuan2405 commented
> a thử thì thấy logic này chưa work ` if the score is lower than 1, the player will lose the game`. em check lại nhe

nãy em refactor chắc đảo lộn logic ban đầu rồi nên nó không work, em có thấy lỗi rồi nên để cái pop-up thông báo game lỗi trước, em đang fix lại file JS với file HTML ạ
![image](https://github.com/user-attachments/assets/8cb81002-9140-4632-a803-e5afab50e32e)

2024-09-21 08:55 UTC, thangphanmoso commented
@MinhTuan2405 oh a cứ tưởng em quên remove. sau em có thể add thêm prefix vào PR title khi nó chưa ready nhe `[Draft] Adding...` (với plan khác thì có thể convert PR thành draft PR)

2024-09-21 09:03 UTC, MinhTuan2405 commented
> @MinhTuan2405 oh a cứ tưởng em quên remove. sau em có thể add thêm prefix vào PR title khi nó chưa ready nhe `[Draft] Adding...` (với plan khác thì có thể convert PR thành draft PR)

vâng anh

2024-09-22 16:07 UTC, thangphanmoso approved these changes

2024-09-23 02:24 UTC, merged